language: python

python:
  - "2.7"
# command to install dependencies
install:

  - pip install -r docs/requirements.txt
  # Enviornments

env:
  - DJANGO=1.11.6 DB=mysql
# command to run tests
script:

  - python manage.py test # or py.test for Python versions 3.5 and below
